export const MAGIC_LINK_EXPIRATION_SECONDS = 900
export const SESSION_TTL_SECONDS = 60 * 60 * 24 * 7
export const PASSWORD_RESET_EXPIRATION_SECONDS = 60 * 60
export const DEFAULT_REQUEST_TIMEOUT_MS = 10_000
export const RETRY_BACKOFF_MS = 500
